### ISSUE TITLE
Send Whatsapp Messages using Pywhatkit

### ISSUE THREAD

**Issue by Saketh-77** [Saketh-77/bulk-message-sender#3]
Acceptance Criteria

1. WhatsApp message should be delivered successfully to the recipient
2. Tab should be auto-closed after each message is sent
3. All edge cases should be covered
4. Testing of the same should be done and evidences need to be attached

**Comment by Saketh-77** [comment]
+1 AC

**Comment by sowmya-dev** [comment]
+AC

**Comment by sowmya-dev** [comment]
+IP

**Comment by Saketh-77** [comment]
TODO: Auto-closing the tab.
